### ISSUE TITLE
[ASK] Is it possible with multiple iPhone device?

### ISSUE THREAD

**Issue by mhaqqiw** [jjunghyup/ios-screen-mirror#1]
If i want to stream with multiple device what i need to do?

**Comment by jjunghyup** [comment]
Sorry for the late reply, no mail alarm.

First, connect multiple devices
Entering `./ios-screen-mirror -devices` will check the `udid` values ​​of the connected devices.

You need to prepare a number of information related to `pushSpec` in advance
In that state, enter `./ios-screen-mirror -udid'<udid>' -pushSpec'<target>'` for multiple devices, respectively.
