### ISSUE TITLE
Get Error when running "go get"

### ISSUE THREAD

**Issue by mhaqqiw** [jjunghyup/ios-screen-mirror#3]
```# github.com/3d0c/gmf
cgo-gcc-prolog:49:2: warning: 'av_init_packet' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/ffmpeg/4.4_2/include/libavcodec/packet.h:487:1: note: 'av_init_packet' has been explicitly marked deprecated here
/usr/local/Cellar/ffmpeg/4.4_2/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'

**Comment by jagdish24** [comment]
@mhaqqiw have you receive any solution for it?

**Comment by sf-luke-cha** [comment]
What is the working environment like? Is it mac os m1?

**Comment by jjunghyup** [comment]
What is the working environment like? Is it mac os m1?

**Comment by luke-cha** [comment]
The library used in this project, `github.com/3d0c/gmf`, is looking at a specific version of `ffmpeg`.
If you look at the following [link](https://github.com/3d0c/gmf/issues/143#issuecomment-949715844), you can check the version that the latest version of `gmf` is looking at.
Update `gmf` to the latest version, and adjust the `ffmpeg` version accordingly.
